### ISSUE TITLE
自动生成excel表格中没有摘要

### ISSUE THREAD

**Issue by babaowin** [hiddenblue/Pubmedsoso#2]
大佬，使用exe直接启动的时候，生成的excel表格中没有摘要（按照展示例子运行），请问是哪里出bug了呀？

**Comment by hiddenblue** [comment]
哈，最近半年一直的忙着写其他的，忘了更新这个了，估计是pubmed的网页格式发生了变化，我明天简单修复一下。

**Comment by hiddenblue** [comment]
家人们，修复了bug了，可以正常使用了

**Comment by babaowin** [comment]
> 家人们，修复了bug了，可以正常使用了

大佬，软件也能更新一下吗？我直接用code用不来（悲）

**Comment by hiddenblue** [comment]
exe release也更新了
